name: Test

on:
  push:
  pull_request:

jobs:
  make-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run tests
        run: make test

  bazel-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
      - name: Run tests
        run: bazel test :all
